#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_TOUCHSCREEN_FT5435_ULYSSE) += focaltech_upgrade_ft5x46.o
obj-$(CONFIG_TOUCHSCREEN_FT5435_ULYSSE) += focaltech_upgrade_idc.o
obj-$(CONFIG_TOUCHSCREEN_FT5435_ULYSSE) += focaltech_upgrade_test.o
